# Generated by Django 4.2.23 on 2025-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cups',
            name='nombre',
            field=models.CharField(max_length=800, unique=True),
        ),
    ]
