# Generated by Django 4.2.23 on 2025-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_obtenido', models.CharField(max_length=100, verbose_name='Título Obtenido')),
                ('institucion_educativa', models.CharField(max_length=100, verbose_name='Institución Educativa')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_culminado', models.DateField(verbose_name='Fecha de Culminado')),
                ('nivel_educativo', models.CharField(choices=[('1', 'Tecnico laboral en salud'), ('2', 'Auxiliar de enfermeria'), ('3', 'Auxiliar en salud oral'), ('4', 'Auxiliar en servicios farmaceuticos'), ('5', 'Auxiliar en atencion Prehospitalaria'), ('6', 'Tecnologo en salud'), ('7', 'Tecnologia en regencia de farmacia'), ('8', 'Tecnologia en atenciaon prehospitalaria'), ('9', 'Tecnologo en laboratorio clinico'), ('10', 'medicina'), ('11', 'enfermeria'), ('12', 'odontologia'), ('13', 'Fisioterapia'), ('14', 'Terapia ocupacional'), ('15', 'Bacteriologia y laboratorio clinico')], max_length=100, verbose_name='Nivel Educativo')),
                ('soporte', models.FileField(upload_to='doc/')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horainico', models.TimeField(blank=True, null=True)),
                ('horafin', models.TimeField(blank=True, null=True)),
                ('horaalmuerzo', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateField(verbose_name='Fecha de Finalizacion')),
                ('tipo_contrato', models.CharField(choices=[('1', 'Contrato a término indefinido'), ('2', 'Contrato a término fijo'), ('3', 'Contrato por obra o labor'), ('4', 'Contrato ocasional, accidental o transitorio'), ('5', 'Contrato de aprendizaje'), ('6', 'Contrato de prestación de servicios'), ('7', 'Contrato sindical ')], max_length=100, verbose_name='Tipo de contrato')),
                ('soporte', models.FileField(upload_to='doc/')),
            ],
        ),
        migrations.CreateModel(
            name='HojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudActualizacionHV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('soporte', models.FileField(default='', upload_to='doc/')),
            ],
        ),
    ]
