# Generated by Django 4.2.23 on 2025-06-17 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_TH', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudactualizacionhv',
            name='personal_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.medico'),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='gestor_th',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.gestor_th'),
        ),
        migrations.AddField(
            model_name='hojavida',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencia_laboral',
            name='hoja_vida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_TH.hojavida'),
        ),
        migrations.AddField(
            model_name='agendames',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.medico'),
        ),
        migrations.AddField(
            model_name='agendadia',
            name='agendames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendadia', to='Gestion_TH.agendames'),
        ),
        migrations.AddField(
            model_name='academico',
            name='hoja_vida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_TH.hojavida'),
        ),
    ]
