# Generated by Django 5.2.3 on 2025-07-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_TH', '0003_agendadia_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendames',
            name='mes',
            field=models.DateField(),
        ),
    ]
