# Generated by Django 4.2.23 on 2025-06-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la Consulta')),
                ('sintomas', models.TextField(verbose_name='Síntomas')),
                ('examen_fisico', models.TextField(verbose_name='Examen Físico')),
                ('enfermedades_base', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enfermedades de Base')),
                ('habitos', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Tabaco', 'Tabaco'), ('Alcohol', 'Alcohol'), ('Drogas', 'Drogas'), ('No', 'Ninguno')], max_length=15, verbose_name='Consumo de sustancias')),
                ('antecedentes_medicos', models.CharField(choices=[('ninguno', 'Ninguno'), ('familiar', 'Familiar'), ('patologico', 'Patológico'), ('no_patologico', 'No Patológico'), ('alergico', 'Alérgico'), ('quirurgico', 'Quirúrgico'), ('farmacologico', 'Farmacológico'), ('inmunologico', 'Inmunológico')], max_length=15, verbose_name='Antecedentes médicos')),
                ('descripcion_antecedente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción del antecedente médico')),
            ],
        ),
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cie10', models.CharField(max_length=20, verbose_name='Código de la enfermedad')),
                ('nombre_cie10', models.TextField(verbose_name='Nombre de la enfermedad')),
                ('descripcion_cie10', models.TextField(verbose_name='Descripción de la enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diagnostico', models.CharField(choices=[('Principal', 'Diagnóstico Principal'), ('Secundario', 'Diagnóstico secundario'), ('Diferencial', 'Diagnóstico Diferencial'), ('Confirmado', 'Diagnóstico Confirmado'), ('Presuntivo', 'Diagnóstico presuntivo'), ('Sindromico', 'Diagnóstico sindrómico'), ('Salud Mental', 'Diagnóstico de Salud Mental'), ('Preventivo', 'Diagnóstico Preventivo'), ('Riesgo', 'Diagnóstico de Riesgo')], max_length=20, verbose_name='Tipo de Diagnóstico')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateField(auto_now_add=True)),
                ('estado_paciente', models.TextField()),
                ('plan_de_manejo', models.TextField(verbose_name='Plan de Manejo')),
                ('evolucion', models.TextField()),
                ('recomendaciones', models.CharField(max_length=200, verbose_name='Recomendaciones')),
                ('interconsultas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Interconsultas')),
                ('plan_de_seguimiento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Plan de Seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_historia', models.CharField(max_length=15, verbose_name='Numero de historia')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('Nro_folio', models.PositiveIntegerField(blank=True, null=True)),
                ('anamnesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Historia_clinica.anamnesis')),
                ('diagnostico', models.ManyToManyField(related_name='historias_clinicas', to='Historia_clinica.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Paraclinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='Resultados de los exámenes')),
                ('analisis', models.TextField(blank=True, null=True, verbose_name='Análisis de los resultados')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.FloatField(verbose_name='Frecuencia Cardiaca')),
                ('presion_arterial', models.FloatField(verbose_name='Presión Arterial')),
                ('frecuencia_respiratoria', models.FloatField(verbose_name='Frecuencia Respiratoria')),
                ('temperatura_corporal', models.FloatField(verbose_name='Temperatura Corporal')),
                ('saturacion', models.IntegerField(verbose_name='Saturación')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('talla', models.FloatField(verbose_name='Talla')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='Índice de Masa Corporal')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeProcedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código del procedimiento')),
                ('cantidad', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cantidad')),
                ('descripcion', models.TextField(null=True)),
                ('estado', models.CharField(choices=[('RT', 'Rutinario'), ('UR', 'Urgente'), ('EM', 'Emergencia'), ('PD', 'Pendiente'), ('PG', 'Programado'), ('RA', 'Requiere Autorizacion'), ('NR', 'No Realizado'), ('SP', 'Suspendido')], max_length=2, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('cups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gerencia.cups')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_de_procedimientos', to='Historia_clinica.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=100, verbose_name='Nombre del Medicamento')),
                ('concentracion', models.CharField(max_length=50, verbose_name='Concentracion del Medicamento')),
                ('forma_farmaceutica', models.CharField(max_length=50, verbose_name='Forma Farmaceútica del Medicamento')),
                ('dosis', models.CharField(max_length=50, verbose_name='Dosis')),
                ('via_administracion', models.CharField(choices=[('VO', 'Vía oral'), ('VR', 'Vía rectal'), ('VT', 'Vía tópica'), ('TD', 'Vía transdérmica'), ('VI', 'Vía inhalatoria'), ('IV', 'Vía intravenosa'), ('IM', 'Vía intramuscular'), ('SC', 'Vía subcutánea'), ('IO', 'Vía intraósea'), ('IT', 'Vía intratecal'), ('SL', 'Vía sublingual')], max_length=2, verbose_name='Vía de Administración')),
                ('frecuencia', models.CharField(max_length=20, verbose_name='Frecuencia del Medicamento')),
                ('tiempo_tratamiento', models.CharField(max_length=30, verbose_name='Tiempo del Tratamiento')),
                ('cantidad', models.CharField(max_length=10, verbose_name='Cantidad del Medicamento')),
                ('cantidad_letras', models.CharField(max_length=50, verbose_name='Cantidad en letras')),
                ('posologia', models.CharField(max_length=100, verbose_name='Posología')),
                ('recomendaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recomendaciones')),
                ('formula_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='Historia_clinica.formulamedica')),
            ],
        ),
    ]
