# Generated by Django 4.2.23 on 2025-06-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Historia_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.medico'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paraclinicos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Historia_clinica.paraclinicos'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='signos_vitales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Historia_clinica.signosvitales'),
        ),
        migrations.AddField(
            model_name='formulamedica',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_clinica.diagnostico'),
        ),
        migrations.AddField(
            model_name='formulamedica',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_medica', to='Historia_clinica.historiaclinica'),
        ),
        migrations.AddField(
            model_name='formulamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.medico'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historia_clinica.diagnostico'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucion', to='Historia_clinica.historiaclinica'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.medico'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='cie10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Historia_clinica.cie10', verbose_name='Cie10'),
        ),
    ]
