# Generated by Django 5.2.3 on 2025-06-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='eps',
            field=models.CharField(max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estrato',
            field=models.CharField(choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=1, null=True, verbose_name='Estrato'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_atencion_especial',
            field=models.CharField(choices=[('I', 'Indígena'), ('N', 'Negro'), ('D', 'Desplazado'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Grupo de Atención Especial'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo')], max_length=3, null=True, verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='regimen',
            field=models.CharField(choices=[('RC', 'Régimen Contributivo'), ('RS', 'Régimen Subsidiado'), ('RE', 'Régimen Especial'), ('PA', 'Particular')], max_length=10, null=True),
        ),
    ]
