# Generated by Django 4.2.23 on 2025-06-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Atendida', 'Atendida')], max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
                ('tipo_atencion', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=50)),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerencia.centro_medico')),
            ],
        ),
        migrations.CreateModel(
            name='Info_cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=255)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_citas.cita')),
            ],
        ),
    ]
