# Generated by Django 5.2.3 on 2025-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_citas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
    ]
