# Generated by Django 5.2.3 on 2025-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_citas', '0003_alter_cita_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'atendida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_atencion',
            field=models.CharField(choices=[('presencial', 'presencial'), ('virtual', 'virtual')], max_length=50),
        ),
    ]
