# Generated by Django 5.2.3 on 2025-07-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_citas', '0005_cita_hora_solicitud_alter_cita_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='hora_solicitud',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_asignacion',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
